### ISSUE TITLE
Aliases are not recognized

### ISSUE THREAD

**Issue by thoelze1** [hanslub42/rlwrap#100]
If an alias is set in bash as `alias lsalias="ls"` then `rlwrap lsalias` will fail:

```lsalias: error: Cannot execute lsalias: No such file or directory```

I think that this is because `execvp()` tries to execute `lsalias` directly and is unaware that `lsalias` is a bash alias.

[This project](https://github.com/mmmorris1975/aws-runas) written in golang [added support for aliases](https://github.com/mmmorris1975/aws-runas/issues/16). Would it make sense to add support for aliases to `rlwrap`?

**Comment by hanslub42** [comment]
It may just be a matter of taste, but for me, this goes against the Unix philosophy of "many small tools" with separated concerns, which was the inspriration for `rlwrap` to begin with.

This means that I would rather leave the interpretation of your aliases to the shell itself. You could for example have the following in your `.bashrc`:


    alias lsalias=ls
    function rlwrap {
       command rlwrap bash -i -c "$*" # command to prevent recursion
                                                         # -i to force bash to read .bashrc
     }

Now, if you type 

    $ rlwrap lsalias -l

you will get the expected result. For those cases where you'd want the original behaviour, you could always type

    $ command rlwrap ....

**Comment by thoelze1** [comment]
That makes sense - thank you for explaining! I'll close the issue.
