### ISSUE TITLE
configure cannot find readline on SLES 12

### ISSUE THREAD

**Issue by bjoern2200** [hanslub42/rlwrap#102]
Hello,

I downloaded the current version rlwrap-0.43 and I'm trying to compile it on a SUSE Linux Enterprise Server 12 (x86_64).

When configuring the installation I get the following:

```
host01:~/rlwrap-0.43 # ./configure
...
OPENPTY
configure: checking for pty ranges...
checking for tgetent... no
checking for tgetent in -ltinfo... yes
checking for readline in -lreadline... no
configure: error:
You need the GNU readline library(ftp://ftp.gnu.org/gnu/readline/ ) to build
this program!
```

According to ldconfig the library is there:
```
host02:~/rlwrap-0.43 # ldconfig -p | grep -i readli
        libreadline.so.6 (libc6,x86-64) => /lib64/libreadline.so.6
        libreadline.so.6 (libc6) => /lib/libreadline.so.6
```

What am I missing?

Best regards,
Björn

**Comment by hanslub42** [comment]
Did you install `readline-devel`? If only `readline` is installed then the readline shared libraries will be present on your system, but not e.g. `/usr/include/readline`, and the configure script will complain about that.

This is mentioned in the `INSTALL` file, but maybe not clearly enough:

> If configure complains about missing Xyz (where Xyz can be ncurses, or
> readline) and you are sure that Xyz is installed on your system,
> consider installing Xyz-devel

**Comment by bjoern2200** [comment]
Hi,

I found, that leadline-devel is not included in the default SLES repositories.
You need to add the "SUSE Linux Enterprise Software Development Kit" using YAST2.
Now I could install readline-devel and compile rlwrap.

Many thanks.
