### ISSUE TITLE
Change reverse search behaviour

### ISSUE THREAD

**Issue by vjunior1981** [hanslub42/rlwrap#103]
Hi,

first of all, thanks for this amazing tool.

A quick question: I'm using rlwrap with sqlplus, and it's amazing.
But, I also love the way reverse search works with fuzzy finder ([fzf](https://github.com/junegunn/fzf)).

So, is it possible to change the CTRL-R command to call what is binded to those keys?
```
bindkey|grep '\^R'
"^R" fzf-history-widget
```

So we could have a search like [this](https://ibb.co/xgF6JdR).

best regards,
Vitor Jr.

**Comment by Aeres-u99** [comment]
yupp I would like to have something similar too

**Comment by hanslub42** [comment]
This was already possible using `peco` and the `handle_hotkey` filter. 7111c8df0c49b05945b53cb5ddbacd82cdc13a2b adds `fzf` as an alternative to peco. Use it  by adding:

  "C-f" : rlwrap-hotkey 

to your `.inputrc`, and then call your command with `rlwrap  -z hotkey_handler <command>`

Pressing `CTRL-F` will invoke `fzf` on your history.

(If you 'd rather bind `CTRL-R` you'll have make minor changes to both `.inputrc` and the `hotkey_handler` script itself.)
