### ISSUE TITLE
rlwrap -c ed: fails to open file

### ISSUE THREAD

**Issue by Ygrex** [hanslub42/rlwrap#104]
there is a file *sample.text*:
```
$ rlwrap -c ed 
e sample.text
17
q
```

it fails to open when I try it with filename auto-completion:
```
$ rlwrap -c ed 
e sam<TAB>
... rlwrap expands it to 'sample', I type '.' and press TAB:
e sample.text
sample.text : No such file or directory
?
f
sample.text 
,n
?
```
I expected it to open the existing file *sample.text*, but there is «No such file or directory» which I do not expect

**Comment by hanslub42** [comment]
`rlwrap` is adding a space character after the completion, and that is confusing `ed`

(try `$ ed` and then `e sample.txt<space>`)

`rlwrap` has an option to change or omit this extra character (look for `--extar-char-after-completion` in the manpage). Using this:
 
    $   rlwrap -e '' -c ed # '' is two single quotes, not a double one!

will work as expected.
