### ISSUE TITLE
configure test writing to /proc/<pid>/cmdline fails with 1 CPU

### ISSUE THREAD

**Issue by mtmiller** [hanslub42/rlwrap#105]
When building rlwrap in an environment with only one CPU (e.g. using taskset to set CPU affinity), the configure test that tries to detect whether `/proc/<pid>/cmdline` can be rewritten fails. So it's possible to wind up with a build that doesn't support the `--mirror-arguments` option, even though the system should support it.

It would be best if this feature test could be rewritten to not depend on the ability of the build host to run tasks concurrently. For example, maybe the C test program could read the `cmdline` file instead of sleeping and leaving that to the shell.

See also https://bugs.debian.org/959009

**Comment by hanslub42** [comment]
This was a race between the test program and the configure script, where the the forked test program  hadn't yet `exec()`ed  the `conftest` executable (and, understandably, not gotten around to overwriting its command line) before the configure script tried to read that same command line via the `/proc` filesystem.

Closed by 65780730e652db8603c8480d6e99f0e8ec0e7120 (now we re-try the test a couple of times)
