### ISSUE TITLE
Assign behaviour to SIGINT

### ISSUE THREAD

**Issue by vinipsmaker** [hanslub42/rlwrap#106]
Hi, I've tried to customize the hotkey for `C-c` by putting this in the `.inputrc` file:

```
$if luajit
    "\C-c": kill-whole-line
$endif
```

But `rlwrap` keeps sending `C-c` to the `luajit` program which is awful given default `luajit` behaviour is to just quit the session (and lose all the environment I was working on).

**Comment by hanslub42** [comment]
By default, `C-c` is caught by the terminal (which then sends a `SIGINT to the foreground process group) and is never read by`rlwrap` (let alone `readline`)

However, calling `stty intr undef` before `rlwrap luajit` will make the terminal pass `C-c` to `rlwrap` where it then can be interpreted any way you see fit.
