### ISSUE TITLE
Adding accept-line bindings to .inputrc causes rlwrap to redundantly echo input lines

### ISSUE THREAD

**Issue by dkcasset** [hanslub42/rlwrap#107]
Summary:

In some cases these bindings in .inputrc cause input lines to be echoed twice when running rlwrap in an interactive shell.

"\C-j": accept-line
"\C-m": accept-line

An example where the extra echo occurs in the shell:
$ rlwrap dc
q
q <---- redundant input line
$

This issue occurs for the following commands as well:

rlwrap tclsh
rlwrap perl -d -e 1
rlwrap sbcl

Interestingly, this command does not have the extra echo:

$ rlwrap bc -q
quit
$

Details:

I did a web search for this issue and found only one relevant hit:

https://stackoverflow.com/questions/4485129/why-rlwrap-echos-redundantly-what-i-type-from-the-keyboard

It appears that the person was trying to use an SQL program in an interactive shell, which appears to be the identical issue I'm seeing, but they do not give much additional information.

The issue still occurs when compiling rlwrap from this github repo as of yesterday.  I am on Lubuntu 16.04 with fairly recent updates (still it's an old version and is close to end of life).  I don't have any recent linux distributions to try.  I happened to try renaming my .inputrc, after which rlwrap works as you would expect - echoing the input only once.

As to why those two lines are in my .inputrc:

I was looking into customizing .inputrc and the bash has documentation on the bind builtin command:

-p    Display readline function names and bindings in such a way that they can be re-read.

I used bind -p to create my initial .inputrc as a starting point, which added the two bindings associated with the issue.  Supposedly they are the default bindings, but they clearly affect the behavior of rlwrap.

I have no idea if the root cause is in rlwrap or readline(3), but at the very least I wanted to draw attention to this strange behavior.

**Comment by hanslub42** [comment]
As `rlwrap`  manipulates the cursor behind `readline`'s back, it has to bind ENTER to `my_accept_line`, its  own version of the readline function `rl_accept_line`, in order to be certain of the cursor position after the user presses ENTER.

Things get weird when the user decides to keep using  readline's version (by re-binding ENTER)

Commit 7b219f5f9f0255f7f7ab3b7229c1300651762678 makes this impossible by redefining the readline command `accept-line` to `my_accept_line`
