### ISSUE TITLE
[macos] handle_hotkeys script doesn't appear to be executing fzf hotkey search

### ISSUE THREAD

**Issue by vxe** [hanslub42/rlwrap#119]
Specifically fzf search is not being initiated with C-f but other keybindings like C-y also aren't firing, here is what I am doing:

```
$ rlwrap --version
rlwrap 0.45

$ rlwrap -z handle_hotkeys
Usage: rlwrap -z handle_hotkeys <command>
handle hotkeys (but only if bound to 'rlwrap-hotkey' in your .inputrc):
\C-f:   use fzf to choose from history entries that match current input before cursor
\C-n:   edit current history with 'vi +%L' - add empty line (lines) to select (accept) the following line
\C-p:   use peco to choose from history entries that match current input before cursor
\C-t:   show current time in echo area
\C-y:   insert from clipboard
\M-\C-m:   show current time in echo area
Currently bound hotkeys in /Users/vedwin/.inputrc:
"C-f" : rlwrap-hotkey

$ cat ~/.inputrc
"C-f" : rlwrap-hotkey

$ locate handle_hotkeys
/usr/local/Cellar/rlwrap/0.45/share/rlwrap/filters/handle_hotkeys

$ cat ~/.rlwrap-test
comp-1
comp-2
comp-3

$ rlwrap -H ~/.rlwrap-test -S "TEST> " -z "handle_hotkeys" sh -c 'read REPLY && echo $REPLY'
```

of note is handle_hotkeys is not installed in `/usr/share/rlwrap/filters` but rather `/usr/local/Cellar/rlwrap/0.45/share/rlwrap/filters/`  however it is showing up in `rlwrap -z handle_hotkeys` as installed so I assume that is not a factor here

**Comment by hanslub42** [comment]
There are two problems here:

- You should use `\C` for the CTRL key, not just `C`
- There should not be  a space before the `:` (the manpage gets that wrong too, fixed by ad65648)

So, instead of `"C-f" : rlwrap-hotkey`, use `"\C-f":  rlwrap-hotkey`
