### ISSUE TITLE
Use of `-A` (short form) without an argument breaks invocation via Perl's `exec` function

### ISSUE THREAD

**Issue by mklement0** [hanslub42/rlwrap#121]
First things first: Thanks for a great utility.

I don't know if you want to pursue this, and personally I've found a way around the problem, but I thought I'd let you know.

Here's the gist of the my workaround (and my partially speculative diagnosis):

    # --ansi-colour-aware makes rlwrap ANSI-color-aware (so it doesn't get "confused" by colored prompts)
    #    !! Before v0.45, --ansi-colour-aware was ineffective and had NO option-argument.
    #    !! Starting in v0.45, it gained and optional argument, '!', to "bleach" (strip colors from) prompt strings.
    #    !! The implementation is ambiguous, because the optional argument is expected as a *separate* argument, but that is apparently internally compensated for
    #    !! However, when the short form, -A, is used - curiously *only when launched via Per's `exec`* - *not* passing this optional argument *breaks the invocation on v0.45*.
    #    !! Fortunately, using the long form, --ansi-colour-aware, prevents that.

If you want to reproduce the problem, you can download [perli](https://github.com/mklement0/perli/blob/master/bin/perli) (a Perl REPL):

```sh
curl https://raw.githubusercontent.com/mklement0/perli/master/bin/perli -o perli; chmod a+x ./perli`
```

and, inside the script, replace `--ansi-colour-aware` with `-A`, which then breaks invocation of the script, `./perli` (it worked with `-A` in v0.43).

Happens with Perl v5.18.4 (default on macOS Catalina) and v5.28.2 (default on macOS Big Sur).

The curious thing is that executing the very same `rlwrap` command line from `bash` does _not_ fail.

**Comment by hanslub42** [comment]
`rlwrap` uses [`getopt()`](https://en.wikipedia.org/wiki/Getopt) and GNU `getopt_long()` to parse options.

`getopt_long()` reads long options, and, although not in POSIX, works identical on almost all platforms. Long options can take optional arguments (which have to be specified with an `=` like in `--long-option=optional`)

`getopt()` reads short options. Short options don't allow optional arguments, except on GNU systems (where they have to be specified without an intervening space like in `-loptional`)

OSX isn't a GNU system. On non-GNU systems, the short form of options with optional argnumets always need an argument (which can be a nonsense string)

The `-A` short option didn't allow an optional arggument until `rlwrap-0.45`, but it does so in the newest version. This means that e.g.  `rlwrap -A cat` doesn't work anymore on non-GNU systems, so you'll either have to give a dummy argument (`rlwrap -A brumbleslurgh cat`) or use the long option (`rlwrap --ansi-colour-aware cat`)

In any case, it is perferable to use `--long-options` in scripts that have to be (and remain) portable (there are more reasons to do this anyway, like readability) and only use the short options on the command line.

**Comment by mklement0** [comment]
Thanks for the explanation, @hanslub42.

It's commendable that there's a warning, but that warning doesn't show if _another option_ follows `-A` (which is what happened with `perli`):

E.g., on macOS:

```sh
$ rlwrap -A --command-name feline  cat
rlwrap: error: Cannot execute feline: No such file or directory
```

Requiring that an  _optional_  argument to an option be _directly attached_ to the option makes perfect sense, and is indeed the only way to avoid syntactic ambiguity.

If `getopt()` cannot handle optional arguments in this manner, I recommend suggesting `-A' '` rather than `-A brumbleslurgh` as a workaround.

**Comment by hanslub42** [comment]
> It's commendable that there's a warning, but that warning doesn't show if another option follows -A

Actually, it _does_, but not if a _long_ option (`--command-name`) follows a short option with an optional argument (`-A`). Try `rlwrap -A -C feline  cat` and you'll see what I mean. 

Apparently, I assumed that people would either use only long, or only short options (a bit silly, I freely mix them myself)

This is now fixed by  b23e218b044a515f4562b5c363d4c370aafddeb3:

    [hlub@macosx] .../src/rlwrap-0.45 > uname -a 
    Darwin macosx.polarhome.com 11.4.2 Darwin Kernel Version 11.4.2: Thu Aug 23 16:26:45 PDT 2012; root:xnu-1699.32.7~1/RELEASE_I386 i386
    [hlub@macosx] .../src/rlwrap-0.45 > src/rlwrap -A --command-name feline  cat
    rlwrap: warning: on this system, the getopt() library function doesn't
    grok optional arguments, so '--command-name' is taken as an argument to the -A option
    Is this what you meant? If not, please provide an argument
    warnings can be silenced by the --no-warnings (-n) option
    rlwrap: error: Cannot execute feline: No such file or directory

And yes, the `brumbleslurgh` is a bit over the top, just a fancy way to say _whatever_.

**Comment by hanslub42** [comment]
> If getopt() cannot handle optional arguments in this manner, I recommend suggesting -A' ' rather than -A brumbleslurgh as a workaround.

Actually, `rlwrap` didn't offer _any_ suggestions, but now it does, cf 860f24a69ffce4759f4b20d35afaed9212a0e7c0

**Comment by mklement0** [comment]
Thanks for fixing the mixed scenario and adding suggestions.

Example `-A' '` wasn't _only_ meant to be an alternative to a verbose dummy value, but perhaps more importantly showed the dummy argument _directly attached_ to the short option, which is conceptually cleaner.

Naïve question (I haven't looked into the answer): Does the GNU library you use for the _long_ options on all platforms not also support the _short_ ones, but _with_ optional-argument support?

**Comment by hanslub42** [comment]
I don't use the GNU library on most non-linux systems, but it is possible that even there `getopt-long()` supports optional short option arguments. At present `configure` only tests whether `getopt()` supports them, which may well give a different answer. I will have to look into that.

**Comment by hanslub42** [comment]
See e38bd47a2855d9386d7e6f59fae7b196e1d034c4 . On OSX, `rlwrap` now also handles optional arguments to short options (line `-A`)

    # Up to 0.45, rlwrap would test if getopt() understands option strings like "a:b::c" with double colons
    # I now tend to think that that only happens if (POSIX) getopt() is implemented using (GNU) getopt_long(), so this test
    # is actually superfluous. I leave GETOPT_GROKS_OPTIONAL_ARGS alone for the moment, in case some getopt_long() 
    # implementation that doesnt grok double colons turns up:

**Comment by mklement0** [comment]
That's great - thank you.
