### ISSUE TITLE
cloak_and_dagger function not working as expected

### ISSUE THREAD

**Issue by vapniks** [hanslub42/rlwrap#122]
I'm trying to write a filter for sqlite3 that will complete table names.
After looking at the code in the [ftp_filter](https://github.com/hanslub42/rlwrap/blob/master/filters/ftp_filter) demo, I figured out that I should be able to use the prompt handler to obtain the table names, like this:
```
...
my @tables;
my $filter -> new RlwrapFilter;
$filter -> completion_handler(\&complete);
$filter -> prompt_handler(\&prompt);
$filter -> cloak_and_dagger_verbose(1);
$filter -> run;
...
sub prompt {
  my ($prompt) = @_;
  my $response = $filter -> cloak_and_dagger(".tables","sqlite>",1);
  @tables = split $response, /\n/;
  return $prompt;
}
...
```
However, when I try using it, I get some strange behaviour, and am only able to quit by killing it with pkill. 

```
> rlwrap -a -R -z "sqlite_filter" /usr/bin/sqlite3 mydata.db
Loading sqlite3 plugin
SQLite version 3.22.0 2018-01-22 18:45:57
Enter ".help" for usage hints.
cloak_and_dagger question: .tables
cloak_and_dagger response: .tables
sqlite> quit
Error: unknown command or invalid arguments:  "tablesquit". Enter ".help" for help
cloak_and_dagger question: .tables
cloak_and_dagger response: .tables
sqlite>
[1]    6162 terminated  rlwrap -a -R -z "sqlite_filter" /usr/bin/sqlite3
```
I have tried different combinations of flags (`-a` is needed to get rlwrap working at all), but to no avail.
I have also tried using `SELECT name FROM sqlite_master WHERE type='table';` instead of `.tables`, but that caused the same problem.
If I use rlwrap without the filter I have no problem running the `.tables` command.

Is this a bug or am I doing something wrong?

**Comment by hanslub42** [comment]
I cannot reproduce your problem. With the following filter:

    #!/usr/bin/env perl
    
    use lib ($ENV{RLWRAP_FILTERDIR} or ".");
    use RlwrapFilter;
    use strict;
    
    
    # Filter version of "Hello World":my $filter = new RlwrapFilter;
    
    
    
    my @tables;
    my $filter = new RlwrapFilter;
    
    
    $filter -> help_text("Usage: rlwrap [-options] -z null <command>\n".
    		     "a filter that does nothing");
    
    
    #$filter -> completion_handler(\&complete);
    $filter -> prompt_handler(\&prompt);
    $filter -> cloak_and_dagger_verbose(1);
    $filter -> run;
    
    sub prompt {
      my ($prompt) = @_;
      my $response = $filter -> cloak_and_dagger(".tables","sqlite> ",1);
      $filter -> send_output_oob("\$response = $response\n");
      @tables = split ' ', $response; 
      $filter -> send_output_oob("\@tables = qw(" . join(' ', @tables) . ")\n");
      return $prompt;
    }
    
    $filter -> run;
    
 I get the expected response:
 
    [hlub@tatra (master *+%=)] .../grover_projecten/rlwrap > rlwrap -a -R -z test_dagger sqlite3 inschrijvingen.sqlite3
    SQLite version 3.34.0 2020-12-01 16:14:00
    Enter ".help" for usage hints.
    cloak_and_dagger question: .tables
    cloak_and_dagger response: docenten                inschrijvingen          inschrijvingen_reserve
    
    $response = docenten                inschrijvingen          inschrijvingen_reserve
    
    @tables = qw(docenten inschrijvingen inschrijvingen_reserve)
    sqlite> 

 A few possible problems with your code:

- You need to give the _exact_ prompt to `cloak_and_dagger()`, _including_ the space character after the `sqlite>`
- `split()` has the pattern as its _first_ argument. I would use `' '`, i.e. split on whitespace (and hope that table names don't contain spaces)
- `my $filter -> new RlwrapFilter;` should be `my $filter = new RlwrapFilter;` (but that's probably a typo)

**Comment by vapniks** [comment]
OK, I tried your code but got the same problems.  
However, I notice that you are using a more recent version of `sqlite3`. 
After downloading the latest `sqlite3`, and trying again, both your filter and mine worked.

The typos you mention were introduced when I editing the code to copy to github, but "quit" was not a typo; `sqlite3` was removing the initial "." from output, even though I had typed it... strange. That might have something to do with the problem in `sqlite3`.

**Comment by hanslub42** [comment]
Yes, filters are fragile, and filters with `cloak_and_dagger()` are _really_ fragile. `cloak_and_dagger()` is in essence a simplistic version of what `Expect.pm` (for `perl`) and `pexpect` (for `python`)  are doing much better (and with a lot more code). It might be worthwhile to create an "adaptor" between `RlwrapFillter` and those libraries.

**Comment by vapniks** [comment]
Btw, I also discovered that I needed to add `-t dumb` to my rlwrap options in order for it to print completion candidates properly.
