### ISSUE TITLE
Bash completion in rlwrap

### ISSUE THREAD

**Issue by HarrisonMc555** [hanslub42/rlwrap#123]
Is there any way to use Bash's auto-completion while in `rlwrap`? Or is there another way to do what I'm trying to do?

I am trying to script some Git tasks. For part of the behavior, I may need the user to specify a Git branch. My current approach is a simple `branch=$(rlwrap -S "Branch name: " -P default-branch-name -o cat)`. However, it would be great to use the Bash completion that comes with Git. If I'm in an interactive Bash session I can type `git switch <TAB>` and it will auto-complete to branch names.

In order to take advantage of that functionality would I need to wrap `bash` itself? And then make a filter that simply prints the output instead of passing it along to `bash`? I would love to simply something that could invoke `rlwrap` with a specified `bash` function that `rlwrap` would use for completion.

I'm totally open to any suggestions for alternative ways of accomplishing my goal. Thanks for any and all help!

**Comment by hanslub42** [comment]
`rlwrap` can read a completion word list at startup. Writing the output of  `git branch` to a (temporary) file and using that as a completion word list will make `rlwrap` complete branch names.

In `zsh` this is extremely simple:

      branch=$(rlwrap -f =(git branch)  -S "Branch name: " -P default-branch-name -o cat)

In `bash` it is a bit more work (as a `zsh` user I may be overlooking some simpler `bash` solution, of course)

       git branch > branches.tmp ; branch=$(rlwrap -f branches.tmp  -S "Branch name: " -P default-branch-name -o cat)

**Comment by HarrisonMc555** [comment]
Thanks for the tip! That will work for my use case. Two more things:

I had hyphens in my branch names. In order to get this to work, I used the following:

```bash
f=$(mktemp) &&
	git for-each-ref --format='%(refname:short)' refs/heads/ > "$f" && # avoid asterisks
	branch=$(rlwrap -b "" -e "" -f "$f" -S "Branch name: " -P default-branch-name -o cat)
```

It took me a minute to figure out that I needed to put the `-b ""` _before_ the `-f "$f"`, not _after_, but that was just me not reading the man page close enough.

My second question is whether or not there's a way to use bash completions in general? This example was fortunate in that the list of completions was easy to obtain beforehand. If that isn't the case is there a way to hook into the existing Bash completion function? The answer is probably "no" but I'll take any tips you have 😄 

Thanks for the great tool and feedback!

**Comment by hanslub42** [comment]
> My second question is whether or not there's a way to use bash completions in general?

In theory, yes. A [filter](https://github.com/hanslub42/rlwrap/wiki/RlwrapFilter.pm-manpage) could execute a bash completion script from e.g. ` /usr/share/bash-completion/completions/ ` and harvest the completions. Such a filter would be invoked every time you press `TAB`, so the completions would not be limited to a fixed word list like with `rlwrap -f wordlist`

That said,  `rlwrap` is meant to be a handy little tool for quick and dirty solutions, and tapping into the huge `bash` completion ecosystem feels to me a bit like the proverbial tail wagging the dog. But yes, if you really need it, the tail _can_ probably wag the dog....
