### ISSUE TITLE
rlwrap creates /tmp/rlwrap.debug without debuging compiled in

### ISSUE THREAD

**Issue by burbilog** [hanslub42/rlwrap#128]
I installed rlwrap 0.44 from CentOS (8.3) repo and found that rlwrap creates /tmp/rlwrap.debug on any usage. I thought that it's a problem of distro build, removed the package, cloned this repo and compiled it. Nope, it creates zero length file too:

    -rw-r--r-- 1 oracle oinstall 0 May 18 21:46 /tmp/rlwrap.debug

That's a problem, because I use rlwrap as several differen users. If /tmp/rlwrap.debug exists, other users can't run rlwrap anymore because of permission mismatch:

~~~
% rlwrap sqlplus
rlwrap: error: Cannot open  debug log /tmp/rlwrap.debug for appending: Permission denied
~~~

I tried to reconfigure it with ./configure --disable-debug and rebuild, but it did help, rlwrap still can't be ran from various users...

**Comment by hanslub42** [comment]
Good catch.Simply forgot a `if (debug)`....

Closed by 5aa2609a7e4c76f37c721110bcec312d3efa7e2d
