### ISSUE TITLE
Remap binding

### ISSUE THREAD

**Issue by fedoranvar** [hanslub42/rlwrap#129]
Good day to you!

Found a way for fzf search by handle_hotkeys plugin.
I want to use it with Ion shell (https://gitlab.redox-os.org/redox-os/ion)

But i think Ctrl-F is already binded in there.

Is there a way for remapping or maybe creating custom bindings? 

Thank you!

**Comment by hanslub42** [comment]
This is mentioned in `handle_hotkeys.py`:

```

# change the table below if you like, but don't forget to bind the corresponding keys  to 'rlwrap-hotkey' in your .inputrc, or the hotkeys won't work!                                                                                     

keymap = {
    "y" : yank_clipboard,
    "n" : edit_history,
    "p" : peco_history,
    "f" : fzf_history,
    "r" : peco_history,
    "t" : date_in_echo_area
}
```

So, you  should alter the appropriate line in `handle_hotkeys` (`perl` or `python` version, whichever you prefer) , say to `"k": fzf-history`, *and* put a line  `"\C-k":rlwrap-hotkey` in your `.inputrc` as well.

**Comment by fedoranvar** [comment]
@hanslub42 Thank you!
