### ISSUE TITLE
rlwrap leaves terminal in bracketed paste mode

### ISSUE THREAD

**Issue by gsf** [hanslub42/rlwrap#131]
When I run rlwrap, the terminal is left in bracketed paste mode and I need to disable by passing the terminal code (third and fifth commands below are paste of "echo"):

```
$ rlwrap -v
rlwrap 0.45
$ rlwrap echo

$ 00~echo01~
bash: 00~echo01~: command not found
$ printf "\e[?2004l"
$ echo

$
```

This is in the vscode terminal in macos.

**Comment by hanslub42** [comment]
This should now be fixed by 163144062158abe
