### ISSUE TITLE
Provide immutable source archive for 0.45.x the same as was up to 0.44

### ISSUE THREAD

**Issue by jurajlutter** [hanslub42/rlwrap#132]
Please provide immutable source archives in the same was as it was for 0.44 also for 0.45.

Thanks.

**Comment by hanslub42** [comment]
Thanks for pointing out this problem, which is entirely new to me. I never have explicitely attached source archives until now, but, apparently, GitHub only generates (and then caches) the automatically provided archives when needed. After eviction form the cache (which may - or may not - happen) the archive is generated anew, and can then be slightly different (as dates on directories can be different), causing problems for distributors that keep tabs on those archives via e.g. a checksum

Questions:

- Is this indeed the problem that motivated your question?
- Is attaching a tarball (like I have done now) sufficient to prevent it?
-  Should I also add a `md5sum` ? (none of the projects that I looked at actually do that)

**Comment by jurajlutter** [comment]
Answers:
- Yes. I wanted to commit an update for `devel/rlwrap` port in FreeBSD ports (I am a FreeBSD ports committer)
- Yes
- Probably yes (not only md5 but also something more modern, like, SHA2-256 or SHA2-512, too.)

Thanks.

**Comment by hanslub42** [comment]
OK, done
