### ISSUE TITLE
Is it possible to call rlwrap to modify the input line feed?

### ISSUE THREAD

**Issue by Mark-Joy** [hanslub42/rlwrap#134]
Hello,
I just came to know your tool through my deserted search.

Is it possible to call rlwrap to modify the input line feed?
or maybe some source code modifications could make it works? If it need to be so, how hard core it is?

```
echo_to_prompt() {
	rlwrap clear_input_line
	line=$(rlwrap read_input_line)
	rlwrap special_echo "I am being fed to the input line 😞 "
	rlwrap special_keystroke "Tab -> I am self tabbing"
}
```

The `echo_to_prompt` can be bound to key or can be called from terminal. Say it is bound to `Ctrl-k`, in terminal: 
```
$ Prompt is eating... Don't disturb!
```
Bound key `Ctrl-k` pressed. The "Prompt..." line is read, then cleared and replaced by the following. `Tab` key is also emitted
```
$ I am being fed to the input line 😞 
```

**Comment by hanslub42** [comment]
I don't quite understand what you are looking for. Could you please specify the `rlwrap` behaviour you need in something like the following format (change aa, bb, cc according to your use case, and use notations like `<TAB>`, `<NL>`, `<CR>`, `<CTRL+key>` where relevant)


    invocation: $ rlwrap <options> <command> Which <options> and <command> (if relevant)?
    

    command prompts with: aa
    rlwrap changes the prompt to  bb 
    you type: cc
    rlwrap changes that to dd and feeds it to <command>'s input
    command echoes ee to its output (usually ee == dd)
    rlwrap changes the echo'ed text to ff
    command responds with gg
    rlwrap changes that into hh

**Comment by hanslub42** [comment]
Closing. Please re-open with a clearer description of desired behaviour.
