### ISSUE TITLE
Prompts wider than the terminal width are printed a second time upon hitting enter

### ISSUE THREAD

**Issue by drvink** [hanslub42/rlwrap#137]
Problem: Prompts wider than the terminal width are printed a second time upon hitting enter.

Here we are at a prompt:

![rlwrap-atprompt](https://user-images.githubusercontent.com/4315061/133906996-33667ef2-776c-4251-b69d-253a1af93020.png)

We give some input (but have not yet hit enter):

![rlwrap-atprompt-withinput](https://user-images.githubusercontent.com/4315061/133907012-1046a000-d6ba-421f-aaf0-ca59bdba37d7.png)

After hitting enter:

![rlwrap-atprompt-afterprompt](https://user-images.githubusercontent.com/4315061/133907021-d080c5c6-c2b0-48aa-aa03-990c0b1696df.png)

---

This happens regardless of terminal, `TERM` env var, etc.; furthermore, whether `-pGreen`, `-m`, `-M` are used makes no difference. The issue does not go away with an empty `.inputrc` either.

rlwrap 0.43 does not exhibit this issue, so something broke between then and 5aa2609a7e4c76f37c721110bcec312d3efa7e2d (HEAD of master at the time of this writing).

**Comment by hanslub42** [comment]
Thanks for the report! The relevant change since 0.43 is the handling of bracketed paste (having `set enable-bracketed-paste off` in your `.inputrc` will prevent the double printing of (the first line of)  a multiline prompt).


To be continued...

**Comment by drvink** [comment]
Cool, I'm fine to disable bracketed paste temporarily via `rlwrap -C rlwrap` and `.inputrc` `$if rlwrap` since pastes into rlwrap aren't as potentially disastrous as into the shell (lol).

Sorry for submitting a report instead of a PR, I just don't have the cycles to source-dive at the moment. Thanks for looking into it!!

**Comment by hanslub42** [comment]
ebf037e313a236711924a8642c86650722a3b045 should have fixed this. `readline` behaves a bit differently in bracketed-paste mode so that `rlwrap` has to print the prompt anew when accepting a line. It already did this, but on the start of the current line, instead of where the prompt starts (which may be a couple of lines up, if the prompt is wider than the terminal)

This still needs a bit of testing before I merge it into master
