### ISSUE TITLE
rlwrap with $INPUTRC set appends empty line

### ISSUE THREAD

**Issue by leahneukirchen** [hanslub42/rlwrap#144]
With no $INPUTRC it works:

```
% rlwrap echo foo 
foo
%
```

With $INPUTRC set to any value, it adds an empty line at the end:

```
% INPUTRC=/dev/null rlwrap echo foo 
foo

%
```

(same for a legit INPUTRC, but may be easier to debug this way.)

```
% rlwrap --version
rlwrap 0.45
```

**Comment by vlnx** [comment]
https://lists.gnu.org/archive/html/bug-readline/2021-05/msg00001.html
Just tracked it down to there for now, been bugging me for awhile.

**Comment by leahneukirchen** [comment]
Good catch, I wanted to disable this anyway. %)

**Comment by hanslub42** [comment]
Not `rlwrap`-specific? Closing.
