### ISSUE TITLE
Save to history immediately after input is entered

### ISSUE THREAD

**Issue by DUOLabs333** [hanslub42/rlwrap#152]
Currently, it seems that rlwrap only saves an input to file if the program is exited properly (ie, not with `Ctrl+D`). However, if you do `Ctrl+D`, history is not saved.

**Comment by hanslub42** [comment]
`rlwrap` always saves its history whenever it exits, irrespective of the cause of the exit, which may be the `rlwrap`ped program exiting, seeing a `CTRL+D` of getting a signal that causes it to exit

> if you do Ctrl+D, history is not saved.

On my machine, it is, which means that I cannot reproduce the problem

Can you hive a little more information: what command are you `rlwrap`ping, what input are you entering, etc.

NB: from the title of this issue I expected a different request: that `rlwrap` should have an option to always immediately update the history file after each input line, like with the `zsh` option `INC_APPEND_HISTORY`

This is indeed something to look into, but not needed to solve your issue.

**Comment by DUOLabs333** [comment]
> NB: from the title of this issue I expected a different request: that rlwrap should have an option to always immediately update the history file after each input line, rather like the zsh option INC_APPEND_HISTORY

This is exactly what I'm asking for. I am using `rmaxima`, which is basically `rlwrap maxima`.

**Comment by hanslub42** [comment]
> This is exactly what I'm asking for

OK, this is doable and may be useful in some situations. I'll mark this as a feature request

But you also mentioned:

> However, if you do Ctrl+D, history is not saved.

This would be an `rlwrap` bug. Can you elaborate?

**Comment by DUOLabs333** [comment]
I enter in some maxima expression and press enter. If I press Ctrl+D, then restart it, the input is not saved. It's only when I enter in the line and type in `quit();` that it is saved.

**Comment by hanslub42** [comment]
I cannot reproduce the problem. Maybe the maxima people can help?

**Comment by DUOLabs333** [comment]
I'm on maxima 5.44.0

**Comment by hanslub42** [comment]
In this kind of cases (i.e. a bug I cannot reproduce), please:

- build `rlwrap` from source, using `./configure --enable-debug` 
- run `rlwrap --debug <command>` (where `<command>` is e.g. `maxima`)
- make sure  to trigger the unexpected behaviour (e.g. quit using `CTRL+D`)
- send me the resulting `/tmp/rlwrap.debug`

**Comment by DUOLabs333** [comment]
It seems to be specific to Konsole, as xterm works fine.

**Comment by DUOLabs333** [comment]
Found the problem -- it was a user error.
