### ISSUE TITLE
SIGSEGV when pasting after a Ctrl+V

### ISSUE THREAD

**Issue by demostanis** [hanslub42/rlwrap#153]
`rlwrap cat`
Pressing Ctrl+V
Pasting on my terminal some random text with Ctrl+Shift+V
Pressing Enter
leads to
`rlwrap: Oops, crashed (caught SIGSEGV) - this should not have happened!
If you need a core dump, re-configure with --enable-debug and rebuild
Resetting terminal and cleaning up...`

**Comment by hanslub42** [comment]
I need some information to have any chance  to reproduce and investigate:

- What is your `.inputrc`?
- Which terminal emulator?
- If you're not on linux: which OS?




-

**Comment by demostanis** [comment]
Oops, sorry for forgetting basic information in the initial report...
`~/.inputrc`:
`set editing-mode vi`
Terminal: xfce4-terminal (can reproduce in kitty and alacritty)
Arch Linuxxxxxxx

**Comment by hanslub42** [comment]
Thanks! I cannot reproduce, however. A few more questions, therefore:

- Which `rlwrap` version (`rlwrap -v`)?
- Which `readline` version ?

The fact that the bug occurs after a `quoted-insert` (bound to `CTRL+V` by default) and a subsequent paste (which will enter a  [bracketed paste marker](https://ipwnponies.github.io/programming/2021/02/13/bracketed-paste-mode.html) before the pasted text) is suspicious: there have been a few `rlwrap` releases that [didn't get bracketed-paste quite right](https://github.com/hanslub42/rlwrap/issues/113) 

If my hunch is correct, it might help to put a `set enable-bracketed-paste off` in your `.inputrc`

**Comment by hanslub42** [comment]
I suspect (though I'm by no means certain) that this is related to #167

Closing (until someone can reproduce this on the newest `rlwrap`)
