### ISSUE TITLE
option rlwrap displays prompt at cursor position

### ISSUE THREAD

**Issue by nkh** [hanslub42/rlwrap#157]
echo -e "\e[H" ; command=$(rlwrap -p'0;33' -S 'ftl > ...)

I put the cursor at the top left of the screen but the prompt appears in the line under it, is there any way to fix this?

**Comment by hanslub42** [comment]
Try:

    echo -ne "\e[H"; # etc

(the -n prevents `echo` from printing a newline at the end)
