### ISSUE TITLE
Press Enter twice to send a command with weird suffix

### ISSUE THREAD

**Issue by m1ndcr4ck** [hanslub42/rlwrap#159]
I've updated Kali Linux recently to Version "2022.2" so I guess some update is causing this bug:

Using the following command with netcat  `sudo rlwrap nc -nlvp 443 ` without extra flags and I got a reserve shell connection successfully but I'm experiencing that when trying to send a command I have to press enter twice and the command show as illustrated in the image attached with a `^M ` character
![image](https://user-images.githubusercontent.com/80456322/170296419-c019e826-4fd1-41c2-8eb2-d8539f60f54c.png)

**Comment by hanslub42** [comment]
sudo rlwrap nc -nlvp <port> <shell_cmd> 

... starts a server - why would you want to use rlwrap there - it won't do anything, as the server doesn't  expect input from your terminal.

It is on the client side, i.e. when connecting with `nc  localhost <port>` where `rlwrap` can be useful

      rlwrap -p -S"shell > " nc  localhost <port>
