### ISSUE TITLE
brew install for rlwrap fails on a mac (m1 arm)

### ISSUE THREAD

**Issue by brando90** [hanslub42/rlwrap#163]
I have mac and I had this software installed before and working so not sure what changed. This is the commands:
```
(meta_learning) brandomiranda~ ❯ rlwrap sertop --printer=human

zsh: command not found: rlwrap
(meta_learning) brandomiranda~ ❯ rlwrap
zsh: command not found: rlwrap
(meta_learning) brandomiranda~ ❯ brew install rlwrap
Warning: No available formula with the name "rlwrap".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
(meta_learning) brandomiranda~ ❯ brew uninstall rlwrap
Error: No available formula with the name "rlwrap".
(meta_learning) brandomiranda~ ❯ brew reinstall rlwrap
Error: No available formula with the name "rlwrap".
(meta_learning) brandomiranda~ ❯ brew install rlwrap
fatal: Could not resolve HEAD to a revision
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).

You have 2 outdated casks installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

Warning: No available formula with the name "rlwrap".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
(meta_learning) brandomiranda~ ❯ rlwrap
zsh: command not found: rlwrap
```

I am not sure if it has something to do with my m1 chip arm...but I thought I had it working in my m1 machine. Does brew know what type of mac I have? Does the brew command work for the x86 arch at least?

also the brew formula exists https://formulae.brew.sh/formula/rlwrap but it says it doesn't...?! Why?

-----

see the website:

[![enter image description here][1]][1]

my mac is a Monterrey 12.5.1, it should work...?

-----

related links:
- saw this but it's for linux: https://bjornnaessens.wordpress.com/2012/08/14/installing-rlwrap-on-linux-saves-you-time/
- saw https://stackoverflow.com/questions/15093519/rlwrap-mac-os-x-install-error but our errors are different
- saw https://stackoverflow.com/questions/47405342/getting-error-to-install-rlwrap but uses yum? what is that? scared of running weird commands...
- cross: https://www.reddit.com/r/apple/comments/xf2hoh/how_does_one_install_rlwrap_on_a_mac_os/ and https://github.com/ejgallego/coq-serapi/issues/279

  [1]: https://i.stack.imgur.com/tjx2t.png

-----

original: https://stackoverflow.com/questions/73725834/how-does-one-install-rlwrap-on-a-mac-os

**Comment by hanslub42** [comment]
Did you try `brew search rlwrap`? See .e.g. https://stackoverflow.com/questions/37635486/why-cant-brew-find-a-specific-known-formula

This is not a rlwrap-secific problem, closing
