### ISSUE TITLE
The rlwrap program occasionally fails on several Solaris machines creating a fault alert

### ISSUE THREAD

**Issue by bweyn** [hanslub42/rlwrap#169]
On our Solaris servers we have rlwrap 0.45 running. The rlwrap program occasionally fails on several Solaris machines creating a fault alert
These issues probably appear due to a left session. If the session is closed after a disconnect the processes will be killed some time after that.

**Comment by hanslub42** [comment]
Are you able to compile the newest `rlwrap` (`0.46.1`)? `0.45` could (and would) segfault occasionally, see #167 

A left session would have `rlwrap` waiting for input indefiniely, a segfault in those circumstances is not very likely (except when the `rlwrap`ped program is producing output all the time.

**Comment by bweyn** [comment]
That should be possible. I'll investigate with our OS-engineer.

**Comment by bweyn** [comment]
We've succesfully installed version 0.46.1 
Thanks for your help.

**Comment by hanslub42** [comment]
Please re-open if the problem persists! 

In that case, a (`pstack`) stack trace and/or `rlwrap --debug` output from the core dump would help me a lot!
