### ISSUE TITLE
Minor issue about english

### ISSUE THREAD

**Issue by 6502** [hanslub42/rlwrap#174]
There is a minor issue about English in the notification message after wrapping a signal

    myerror(WARNING|NOERRNO, "%s crashed, killed by %s%s.\n%s itself has not crashed, but for transparency,\n" ...

should be

    myerror(WARNING|NOERRNO, "%s crashed, killed by %s%s.\n%s itself has not crashed but, for transparency,\n" ...

i.e. with the comma after "but" (reason is that "for transparency" is an interrupter and it's the part that should be wrapped in commas). It simply felt weird for me so I double checked with a grammar website.

English is not my native language; if this is wrong just ignore.

Fantastic tool by the way...

**Comment by hanslub42** [comment]
Fixed by 94fa64592bf6de78d50b6f7f87815bb2b2637a21 . Closing
