### ISSUE TITLE
Pragma and redifinition warnings on HP-UX with HP aC compiler

### ISSUE THREAD

**Issue by michael-o** [hanslub42/rlwrap#33]
The compiler warns me about:

    cc -DHAVE_CONFIG_H -I. -I..   -I/usr/local/include -DDATADIR=\"/usr/local/share\                                                                     "  -g -c -o completion.o completion.c
    "completion.rb", line 25: warning #2161-D: unrecognized #pragma
      #pragma GCC diagnostic ignored "-Wunused-but-set-variable"
              ^
    
    "completion.rb", line 26: warning #2161-D: unrecognized #pragma
      #pragma GCC diagnostic ignored "-Wunused-function"
              ^
    
    "completion.rb", line 104: warning #2177-D: function "print_list" was declared
              but never referenced
      print_list()
      ^
    
    "completion.rb", line 115: warning #2177-D: function "rbtree_to_string" was
              declared but never referenced
      static char *rbtree_to_string(const struct rbtree *rb, int max_items) {
                   ^
    
    source='term.c' object='term.o' libtool=no \
    DEPDIR=.deps depmode=hp2 /bin/sh ../tools/depcomp \
    cc -DHAVE_CONFIG_H -I. -I..   -I/usr/local/include -DDATADIR=\"/usr/local/share\                                                                     "  -g -c -o term.o term.c
    source='ptytty.c' object='ptytty.o' libtool=no \
    DEPDIR=.deps depmode=hp2 /bin/sh ../tools/depcomp \
    cc -DHAVE_CONFIG_H -I. -I..   -I/usr/local/include -DDATADIR=\"/usr/local/share\                                                                     "  -g -c -o ptytty.o ptytty.c
    source='utils.c' object='utils.o' libtool=no \
    DEPDIR=.deps depmode=hp2 /bin/sh ../tools/depcomp \
    cc -DHAVE_CONFIG_H -I. -I..   -I/usr/local/include -DDATADIR=\"/usr/local/share\                                                                     "  -g -c -o utils.o utils.c
    "utils.c", line 513: warning #2047-D: incompatible redefinition of macro
              "isset" (declared at line 411 of "/usr/include/sys/param.h")
      #define isset(flag) ((flag) ? "set" : "unset")
              ^
    
    "utils.c", line 758: warning #3051-D: standard requires that parameter
              "command_pid" be given a type by a subsequent declaration ("int"
              assumed)
      void mirror_args(command_pid) {
                       ^
    
    "utils.c", line 598: warning #2177-D: function "print_debug_flag" was declared
              but never referenced
      print_debug_flag(int flag, char *explanation) {
      ^
    
Compilations completes though. I am on:

    $ uname -a
    HP-UX <hostname> B.11.31 U ia64 HP-UX

**Comment by hanslub42** [comment]
There are a couple of minor issues here:

- `completion.c` is generated by the preprocessor `rbgen` from [libredblack](http://libredblack.sourceforge.net/). As this uses a skeleton file which cannot know beforehand which functions will be used in the generated code, it contains a few `gcc` pragmas to suppress warnings about unused functions. Your `cc` is not `gcc`, hence it complains both about the `gcc` pragmas _and_ the unused functions.

- The missing type declaration in utils.c:758 was fixed in #23 

- the redefinition of `isset()` in utils.c:513 is a genuine (although harmless) issue. It has been dealt with in 7a379968bac62ba48cc1724758fb7c79da58f99d

**Comment by michael-o** [comment]
Alright, should I try to compile from master again and show the results?

**Comment by hanslub42** [comment]
2015-05-03 18:59 GMT+02:00 Michael Osipov <notifications@github.com>:

> Alright, should I try to compile from master again and show the results?


Yes, please, but note that the warnings about unused functions and
associated GCCC #pragmas won't have disappeared (unless you can use gcc on
your HP/UX machine)

regards

Hans


-- 
Hans Lub +31 (0)6 14818149         PGP key <https://hanslub.org/>
Dolomieten 74, NL 3524 VH Utrecht  hanslub42@gmail.com

**Comment by michael-o** [comment]
Am 2015-05-03 um 19:03 schrieb Hans Lub:
> 2015-05-03 18:59 GMT+02:00 Michael Osipov <notifications@github.com>:
>
>> Alright, should I try to compile from master again and show the results?
>
>
> Yes, please, but note that the warnings about unused functions and
> associated GCCC #pragmas won't have disappeared (unless you can use gcc on
> your HP/UX machine)

I'll do that on Tuesday. The warnings are probably an issue for 
libredblack. Right?

Michael

**Comment by hanslub42** [comment]
> The warnings are probably an issue for  libredblack. Right?

I doubt it. Pragmas may be ignored, and the warnings are harmless - they don't point to any problem in the code itself.

**Comment by michael-o** [comment]
All looks fine now! Though I have found a followup issue with CC. Will open up this separately.
