### ISSUE TITLE
Configure test does ignore that GCC is not present

### ISSUE THREAD

**Issue by michael-o** [hanslub42/rlwrap#34]
I see this while configuring on HP-UX where I have `cc` only.

    Will rlwrap find command's working directory under /proc/<commands pid>/cwd? let's see...
    checking for /proc/15814/cwd/configure.ac... no
    checking whether we can find command line under <opt_proc_mountpoint>/<pid>/cmdline and mirror it by overwriting our own *argv... ./configure[6683]: gcc:  not found.
    kill: 17374: The specified process does not exist.
    no
    
Since configure already checks for the compiler type maybe this could be reused here *not* to invoke GCC.

**Comment by hanslub42** [comment]
Should be fixed  by b3bb25a9a606de5811875714509e9629cd236e82
Could you please confirm?

**Comment by michael-o** [comment]
Charming:

    Will rlwrap find command's working directory under /proc/<commands pid>/cwd? let's see...
    checking for /proc/1552/cwd/configure.ac... no
    checking whether we can find command line under <opt_proc_mountpoint>/<pid>/cmdline and mirror it by overwriting our own *argv... no

**Comment by hanslub42** [comment]
OK, thanks, that looks OK. Closing.
