### ISSUE TITLE
Need RlwrapFilter in python

### ISSUE THREAD

**Issue by hokuda** [hanslub42/rlwrap#43]
RlwrapFilter.pm is a great feature. However, if there is a python version, it would make us happier. I wrote a prototype and its application:-
https://github.com/hokuda/rlwrapfilter.py
https://github.com/hokuda/rljdb
I think I could prove a python version is feasible. Hope you will have a genuine RlwrapFilter in python.

**Comment by hanslub42** [comment]
Great - thanks! Of course a python version is feasible (or a C, Haskell or Cobol version, tor that matter...) I'll have a good look at it, and will try to incorporate it in the next `rlwrap` release!

**Comment by hokuda** [comment]
Hans, thanks a lot for merging and improving it!!!

**Comment by hanslub42** [comment]
@hokuda: Merging: done. Improving: hmmm, I'm not that fluent in python. Feel free to change things. Especially moving from bytes to strings (and back) is fraught with dangers. `rlwrap`, like most Unix commands,  is completely coding-agnostic, and only ever sees streams of bytes, which it never really inspects. Filters look at the content of  those streams, and will want to work with strings ("capitalize Every Word In The Prompt >")

A good (if rather rough) test is `rlwrap -z null.py cat /dev/random` . With `errors="strict"`, the default setting, decode()` will stumble on the random bytes, and the filter will die.

Decoding with `errors="ignore"` seems to  work well, until now. 

Again, thanks for the excellent work!
