### ISSUE TITLE
Use carriage_return and cursor_right if cursor_hpos is unavailable

### ISSUE THREAD

**Issue by hanslub42** [hanslub42/rlwrap#48]
Sometimes (if rarely) `rlwrap` needs to position the cursor someplace on the line (usually at `rl_point`)

Currently it uses terminfo/termcap capability `cursos_hpos`, and just gives up when that is unavailable (as it is under `xterm`).

This causes errors like:

    Assertion failed: term_cursor_hpos != NULL, file term.c, line 212

when e.g. calling `rlwrap-edit-history`

 But most terminals do have `carriage_return` and `cursor_right`, so why not use those whenever `cursor_hpos` is unavailable?

**Comment by hanslub42** [comment]
Closed by e76e1d6

**Comment by 1ChrisTheCreator1** [comment]
Naw, why is it a *BUG.ERRO404* bro
