### ISSUE TITLE
Where is the configure script?

### ISSUE THREAD

**Issue by smprather** [hanslub42/rlwrap#59]

**Comment by hanslub42** [comment]
According to the INSTALL file:

> If  the configure script is not found, you can recreate it, and all of the other files it needs, by:
>
>     aclocal
>     autoconf
>     autoheader
>     automake --add-missing
> 
> or, even shorter:
>
>    autoreconf --install

In my opinion, a source code repository [should not contain any files that are generated by the build process](http://stackoverflow.com/questions/3290908/which-files-generated-by-autotools-should-i-keep-in-version-control-repository) (to prevent a change in e.g. my autotools version from causing massive changes that only serve to clog up the commit log). The same holds for e.g. the manpage, that is generated by `groff` in the build process.

The only exception in the `rlwrap` repository is the file `completion.c` that is generated from `completion.rb` by a rather obscure (and by now considerable bit-rotten) tool [rbgen](http://libredblack.sourceforge.net/).

But you probably have a shiny new Autotools installed on your computer, so there is no need to track  `configure` here

**Comment by smprather** [comment]
Thanks! I wouldn't quite say "shiny new" since I'm at work and not in control of the unix OS I must work on (various versions of Redhat mostly configured for server duty). But, autoreconf --install appeared to work. My bad for not picking up on that in the INSTALL file.

But now I'm getting (if you don't mind me asking here; if you do, I can try to find the proper forum to ask in).

```
make[2]: Entering directory `/remote/us01home20/myles/rlwrap/src'
gcc -DHAVE_CONFIG_H -I. -I..    -DDATADIR=\"/u/myles/share\"  -g -O2 -MT readline.o -MD -MP -MF .deps/readline.Tpo -c -o readline.o readline.c
readline.c: In function ‘handle_hotkey2’:
readline.c:689: error: ‘rl_executing_keyseq’ undeclared (first use in this function)
readline.c:689: error: (Each undeclared identifier is reported only once
readline.c:689: error: for each function it appears in.)

```

**Comment by smprather** [comment]
It appears to be a bug. I removed the reference to this var in the two places it occurs in readline.c and then everything compiled ok.

**Comment by hanslub42** [comment]
Interesting. Which `readline` version do you have?  And what exactly do you mean by "removing" this variable?

I wouldn't call it a bug, but a new (and undocumented) dependency, as `rl_executing_keyseq` is declared only in newer `readline` versions (see #60)

Anyway, thanks for the report!

**Comment by smprather** [comment]
`/*DPRINTF2(DEBUG_READLINE, "hotkey press: %x (%s)", hotkey, mangle_string_for_debug_log(rl_executing_keyseq, MANGLE_LENGTH));*/`

```
/* filter_food = key + tab + prefix + tab + postfix + tab + history + tab + histpos  + '\0' */
  length = strlen(rl_line_buffer) + strlen(history) + MAX_HISTPOS_DIGITS + 5;
  filter_food = mymalloc(length);
  sprintf(filter_food, "lakjsdlfkajsdklfj"); /* this is the format that the filter expects */
```

**Comment by hanslub42** [comment]
Yeah, okay, that is healing the patient by radical amputation. I'll try to come up with a nice wooden leg instead of the bloody stump you've left him with ... :-)

**Comment by smprather** [comment]
Looks like my system has readline 6.0 on it.

Yeh :), I just wanted to see if I could get it through easily to help you debug.

I just compiled my own readline 6.3. I'll see if I can get rlwrap's configure to find it instead of the /lib64 version.

**Comment by hanslub42** [comment]
With 7b3d7e43548 `rlwrap` should compile with older `readline` versions as well. The "wooden leg" is an implementation where the filter only sees the last byte of the hotkey sequence. As long as those last bytes are different for each hotkey everything should be fine and dandy.
