### ISSUE TITLE
rl_executing_keyseq undeclared

### ISSUE THREAD

**Issue by hanslub42** [hanslub42/rlwrap#60]
Apparently, ee17ef2d2a1f490a  makes `rlwrap` require a newer `readline` than it used to:

    readline.c:689: error: ‘rl_executing_keyseq’ undeclared (first use in this function)

Until 6.3 (and on RedHat, [even with 6.3](https://bugzilla.redhat.com/show_bug.cgi?id=1120050)) `readline` didn't export a variable `rl_executing_keyseq`

Is it reasonable to require readline >= 6.3? Is there an alternative that would work with multi-byte hotkeys (or are those impossible in readline<6.3 anyway)

**Comment by hanslub42** [comment]
`readline-6.3` was released february 2014. There will be many installations that have an older version (until now `rlwrap` required `readline` >= 4.2. `readline-4.2` was released  in 2001)

A possible workaround would be:

    #if !HAVE_RL_EXECUTING_KEYSEQ
     char *rl_executing_keyseq = mysavestring("?");
     *rl_executing_keyseq = hotkey; /* this limits hotkeys to a single byte */
    #endif

**Comment by hanslub42** [comment]
Should have been fixed by 7b3d7e435481f6fec

**Comment by smprather** [comment]
Works now. Thanks Hans!
