### ISSUE TITLE
Question: send command to child when terminal size change

### ISSUE THREAD

**Issue by co-dh** [hanslub42/rlwrap#62]
Hello:
    I have a command (kdb+ q, close sourced )that is not able to handle SIGWINCH, is it possible for rlwrap to send a string to it when caught SIGWINCH?

Thanks in advance.

**Comment by hanslub42** [comment]
I would rather not encumber `rlwrap` with all kinds of _ad hoc_ functionality. On the other hand, there is the filter mechanism which allows one to plug everything but the kitchen sink into `rlwrap`

One could extend the `RlwrapFilter` class with a `signal_handler` method. Communicating with a filter directly from a signal hander would open a can of worms, but the handler could set a flag to make `rlwrap` communicate with the filter at some later moment.

The filter mechanism is in the middle of a major (and long overdue) re-write, which I would prefer to finish first, but this could be put on a separate branch.

**Comment by hanslub42** [comment]
See [here](https://stackoverflow.com/questions/44477784/how-do-i-reopen-system-in-after-eof-or-prevent-eof-entirely/44478670#44478670) for someone who expected `rlwrap` to "catch signals", whatever that means. A `signal_handler` method could, at the very least:

- ignore a signal
- substitute a different signal (like the current `--pass-sigint-as-sigterm` option
- generate some input for the underlying command (like in co-dh's proposal)
- generate some output (like" CTRL-C ignored")

**Comment by hanslub42** [comment]
Signal handling in filters has been added in b106f3c819fa546c7f87169d0ba83bb7dd1aabbc

Replying on what I wrote 3 years ago:

> A signal_handler method could, at the very least:
> 
> - ignore a signal
>      -  by having the filter return "0" 
>  - substitute a different signal (like the current --pass-sigint-as-sigterm option)
>    -  by having the filer return a different signal 
>  - generate some input for the underlying command (like in co-dh's proposal)
>    - using the `cloak_and_dagger()` method
>   - generate some output (like" CTRL-C ignored")
>        - using `send_output_oob()` (to output text to `rlwap` "out-of-band"

I don't know how robustly this is  going to work, as the whole filter I/O runs _withn_ the signal handler. _Caveat emptor_!

**Comment by co-dh** [comment]
Thank you @hanslub42 . Feel that we changed the history :)
