### ISSUE TITLE
No .configure script?

### ISSUE THREAD

**Issue by doyouhas** [hanslub42/rlwrap#71]
Okay am I high or something or is the .configure script completely missing from this repository? Cloned it and proceeded to install when I realized it was absent.

Regards

**Comment by hanslub42** [comment]
No, there is none. See #59 (or the `INSTALL` file) for the reason why, and for a recipe to generate it yourself.

**Comment by doyouhas** [comment]
Sorry I am somewhat of a noob @ compiling from source. Thanks for linking me to this info, appreciate it. Got it working no problem now :+1:
