### ISSUE TITLE
malloc failure w/o input?

### ISSUE THREAD

**Issue by adavies42** [hanslub42/rlwrap#76]
I recently had a long-running process (inside a GNU screen session, if that's relevant), which was producing (substantial) output, but which I hadn't typed anything into in hours, fail with "Out of memory: tried in vain to allocate 5 bytes". When exactly does rlwrap need to acquire new memory under these circumstances?

I think I've seen this once before, and I don't have a reproducible testcase yet.

**Comment by hanslub42** [comment]
>  When exactly does rlwrap need to acquire new memory under these circumstances?

In order not to run into all kinds of artificial size limits, string manipulations in `rlwrap` use dynamically allocated strings, so there is a lot of allocating (and freeing) going on all the time.

The most helpful would be if you could build `rlwrap` with the `--enable-debug` configure flag, and then run

    $ rlwrap -d 15 <your long running program>

do a <kbd>CTRL-C</kbd> after some time - even if we don't run out of memory the memory leak should be easy enough to spot (in the debug file `/tmp/rlwrap.debug`)

**Comment by hanslub42** [comment]
I have not been able to reproduce this.  `rlwrap cat <huge_file_of_random_bytes>` doens't leak memory, which would be the most obvious (although not sole conceivable) cause of this problem. Closing for now.
