### ISSUE TITLE
./configure: No such file or directory

### ISSUE THREAD

**Issue by krux02** [hanslub42/rlwrap#87]
The installation manual explicitly mentions that I should build using ./configure. But there is no configure in the repository.

**Comment by RiverIntheSky** [comment]
it lacks autoreconf -i

**Comment by krux02** [comment]
Thanks I found this out by now. I still think it should be mentioned in the manual.

**Comment by hanslub42** [comment]
The instructions to use `autoreconf` are in the `INSTALL` file, where they belong i.m.h.o, rather than in the manual:

> INSTALLATION

> First, unzip the tarball or clone the git repository (git clone
> https://github.com/hanslub42/rlwrap.git). Then go to the rlwrap
> directory. After a 'git clone' you will not yet have a configure file; 
> build one using autotools (e.g. autoreconf --install, cf. the section 
> BUILD PROBLEMS below))
