### ISSUE TITLE
Warning when running rlwrap sqlplus with -U option

### ISSUE THREAD

**Issue by bsjerps** [hanslub42/rlwrap#99]
When running rlwrap with Oracle sqlplus you typically want to hide the command line as it could contain userid/password, so the -U (--mirror-arguments) option can be used for that.
Sometimes when exiting sqlplus, I get this warning:

rlwrap: warning: cannot mirror command's command line, as (null) is unreadable: No such file or directory

It seems to happen when sqlplus itself exits with a non-zero return code.

Recreate issue:
Connect as some non-sys user:
`rlwrap -U sqlplus soe/soe`

Then run this script (named err.sql):
```
WHENEVER SQLERROR EXIT SQL.SQLCODE
select foo from bar;
```
```
SOE:DB01 > @err
select foo from bar
                *
ERROR at line 1:
ORA-00942: table or view does not exist


rlwrap: warning: cannot mirror command's command line, as (null) is unreadable: No such file or directory

warnings can be silenced by the --no-warnings (-n) option
Disconnected from Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, Automatic Storage Management, OLAP, Advanced Analytics
and Real Application Testing options
```

**Comment by hanslub42** [comment]
closed by d320f5e8ef3c0076d7940321002966f4e2da9ca0
